### ISSUE TITLE
navigation bar not responding

### ISSUE THREAD

**Issue by vinay769** [Ajinkgupta/DjangXel#1]
**navigation bar **
whenever i click on explore or setting the purple color is stuck on home button only

1. remove the defalut from home and set position to relative

**Comment by Ajinkgupta** [comment]
Thank you for taking the time to report this issue. I'm happy to inform you that I have investigated the problem and fixed it by removing the default from the home button and setting the position to relative. I used the active URL path request to make sure that the correct button is highlighted when clicked. Thank you again for your help in identifying this issue!
 
 [https://github.com/Ajinkgupta/DjangXel/commit/2286a163b91c88d18dc59fc5e6355f1ba65e442a](https://github.com/Ajinkgupta/DjangXel/commit/2286a163b91c88d18dc59fc5e6355f1ba65e442a)

**Comment by Ajinkgupta** [comment]
fixed issue
